# -*- coding: utf-8 -*-
"""Final_One_DDoS_Multi_Class_Implemented.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PG7cUI-3oUmEMIyq-QQPqNysOnDTCssa

# **Data Loading And Preprocessed with Proper Labeling**
"""

# ============================================================
# MERGE MULTIPLE DDoS DATASETS INTO ONE CSV
# ============================================================

import pandas as pd
import os
from glob import glob

# =========================
# 1. SET FOLDER PATH
# =========================
folder_path = "/content/ddos_testing_datasets"   # change this

# Get all CSV files
files = glob(os.path.join(folder_path, "*.csv"))

print(f"Total files found: {len(files)}")

# =========================
# 2. READ ALL FILES
# =========================
dfs = []

for file in files:
    try:
        df = pd.read_csv(file)

        # Clean column names (remove spaces)
        df.columns = df.columns.str.strip()

        print(f"Loaded: {file} → Shape: {df.shape}")

        dfs.append(df)

    except Exception as e:
        print(f"Error reading {file}: {e}")

# =========================
# 3. FIND COMMON COLUMNS
# =========================
common_cols = set(dfs[0].columns)

for df in dfs[1:]:
    common_cols = common_cols.intersection(set(df.columns))

common_cols = list(common_cols)

print(f"\nCommon columns count: {len(common_cols)}")

# =========================
# 4. FILTER DATAFRAMES
# =========================
dfs_filtered = []

for df in dfs:
    dfs_filtered.append(df[common_cols])

# =========================
# 5. MERGE ALL
# =========================
merged_df = pd.concat(dfs_filtered, ignore_index=True)

print("\nFinal Merged Shape:", merged_df.shape)

# =========================
# 6. SAVE FINAL DATASET
# =========================
merged_df.to_csv("final_testing_ddos_dataset.csv", index=False)

print("\n✅ Merged dataset saved as: final_merged_ddos_dataset.csv")

# ============================================================
# LABEL CREATION FOR RESEARCH (BINARY + MULTI-CLASS)
# ============================================================

import pandas as pd

# Load datasets
train_df = pd.read_csv("final_training_ddos_dataset.csv")
test_df  = pd.read_csv("final_testing_ddos_dataset.csv")

# =========================
# 1. CLEAN LABELS
# =========================
def clean_label(x):
    x = str(x)
    if "BENIGN" in x.upper():
        return "Benign"
    else:
        return x   # keep attack name

train_df["Label"] = train_df["Label"].apply(clean_label)
test_df["Label"]  = test_df["Label"].apply(clean_label)

# =========================
# 2. BINARY LABEL
# =========================
train_df["Binary_Label"] = train_df["Label"].apply(
    lambda x: 0 if x == "Benign" else 1
)

test_df["Binary_Label"] = test_df["Label"].apply(
    lambda x: 0 if x == "Benign" else 1
)

# =========================
# 3. MULTI-CLASS LABEL
# =========================
train_df["Attack_Type"] = train_df["Label"]
test_df["Attack_Type"]  = test_df["Label"]

# =========================
# 4. CHECK DISTRIBUTION
# =========================
print("\nTraining Distribution:")
print(train_df["Attack_Type"].value_counts())

print("\nTesting Distribution:")
print(test_df["Attack_Type"].value_counts())

# =========================
# 5. SAVE UPDATED DATASETS
# =========================
train_df.to_csv("train_labeled.csv", index=False)
test_df.to_csv("test_labeled.csv", index=False)

print("\n✅ Labeled datasets saved!")

# ============================================================
# FIX LABEL INCONSISTENCY (VERY IMPORTANT)
# ============================================================

def normalize_attack_name(x):
    x = str(x)

    if "BENIGN" in x.upper():
        return "Benign"

    # Remove "DrDoS_" prefix
    if "DrDoS_" in x:
        x = x.replace("DrDoS_", "")

    # Standardize naming
    x = x.replace("UDP-lag", "UDPLag")
    x = x.replace("WebDDoS", "Web")

    return x

# Apply to both datasets
train_df["Attack_Type"] = train_df["Attack_Type"].apply(normalize_attack_name)
test_df["Attack_Type"]  = test_df["Attack_Type"].apply(normalize_attack_name)

# Check again
print("\nTraining Distribution (Fixed):")
print(train_df["Attack_Type"].value_counts())

print("\nTesting Distribution (Fixed):")
print(test_df["Attack_Type"].value_counts())

# Save again
train_df.to_csv("train_fixed.csv", index=False)
test_df.to_csv("test_fixed.csv", index=False)

print("\n✅ Labels normalized successfully!")

import pandas as pd
from sklearn.utils import resample

# Load dataset
train_df = pd.read_csv("train_fixed.csv")

# =========================
# 1. SMART MERGING
# =========================
train_df["Attack_Type"] = train_df["Attack_Type"].replace({
    "UDPLag": "UDP",   # Safe merge
})

# (Optional advanced grouping)
# train_df["Attack_Type"] = train_df["Attack_Type"].replace({
#     "NetBIOS": "TCP_Service",
#     "MSSQL": "TCP_Service",
#     "LDAP": "TCP_Service"
# })

# =========================
# 2. BALANCING
# =========================
df_list = []

for attack in train_df["Attack_Type"].unique():
    df_class = train_df[train_df["Attack_Type"] == attack]

    if len(df_class) < 2000:
        df_class = resample(
            df_class,
            replace=True,
            n_samples=2000,
            random_state=42
        )

    df_list.append(df_class)

train_balanced = pd.concat(df_list)

# =========================
# 3. CHECK
# =========================
print(train_balanced["Attack_Type"].value_counts())

# =========================
# 4. SAVE
# =========================
train_balanced.to_csv("train_balanced.csv", index=False)

print("\n✅ Balanced dataset ready!")

"""# **Actually Training With XGBClassifier**"""

# ============================================================
# TWO-STAGE DDoS DETECTION SYSTEM (RESEARCH IMPLEMENTATION)
# ============================================================

import pandas as pd
import numpy as np
import joblib

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier
import seaborn as sns
import matplotlib.pyplot as plt

# ============================================================
# 1. LOAD DATA
# ============================================================
train_df = pd.read_csv("train_balanced.csv")
test_df  = pd.read_csv("test_fixed.csv")

# ============================================================
# 2. FEATURE SELECTION
# ============================================================
features = [
    "Flow Duration",
    "Total Fwd Packets",
    "Fwd Packets Length Total",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Fwd IAT Mean",
    "Fwd IAT Min",
    "Fwd IAT Std",
    "Total Backward Packets",
    "Bwd Packets Length Total",
    "Down/Up Ratio",
    "Packet Length Mean",
    "Packet Length Std",
    "Avg Packet Size",
    "SYN Flag Count",
    "ACK Flag Count",
    "RST Flag Count",
    "Protocol"
]

# ============================================================
# 3. PREPARE DATA
# ============================================================
X_train = train_df[features].copy()
X_test  = test_df[features].copy()

# Cleaning
X_train.replace([np.inf, -np.inf], np.nan, inplace=True)
X_test.replace([np.inf, -np.inf], np.nan, inplace=True)

X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ============================================================
# 4. STAGE 1: BINARY MODEL
# ============================================================
print("\n===== STAGE 1: BINARY CLASSIFICATION =====")

y_train_bin = train_df["Binary_Label"]
y_test_bin  = test_df["Binary_Label"]

binary_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    eval_metric="logloss",
    random_state=42
)

binary_model.fit(X_train_scaled, y_train_bin)

y_pred_bin = binary_model.predict(X_test_scaled)

print("\nBinary Classification Report:")
print(classification_report(y_test_bin, y_pred_bin))

# Confusion Matrix
cm_bin = confusion_matrix(y_test_bin, y_pred_bin)

plt.figure(figsize=(5,4))
sns.heatmap(cm_bin, annot=True, fmt='d', cmap='Blues')
plt.title("Binary Confusion Matrix")
plt.show()

# ============================================================
# 5. STAGE 2: MULTI-CLASS MODEL (ONLY DDoS)
# ============================================================
print("\n===== STAGE 2: ATTACK TYPE CLASSIFICATION =====")

# Filter only DDoS samples
train_ddos = train_df[train_df["Binary_Label"] == 1]
test_ddos  = test_df[test_df["Binary_Label"] == 1]

X_train_ddos = train_ddos[features]
X_test_ddos  = test_ddos[features]

# Scaling (reuse same scaler)
X_train_ddos = scaler.transform(X_train_ddos)
X_test_ddos  = scaler.transform(X_test_ddos)

# Encode attack types
le_multi = LabelEncoder()
y_train_multi = le_multi.fit_transform(train_ddos["Attack_Type"])

# IMPORTANT: Filter test labels that exist in training
known_classes = set(train_ddos["Attack_Type"].unique())

test_ddos_known = test_ddos[test_ddos["Attack_Type"].isin(known_classes)]

X_test_known = scaler.transform(test_ddos_known[features])
y_test_multi = le_multi.transform(test_ddos_known["Attack_Type"])

# Train model
multi_model = XGBClassifier(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    eval_metric="mlogloss",
    random_state=42
)

multi_model.fit(X_train_ddos, y_train_multi)

y_pred_multi = multi_model.predict(X_test_known)

print("\nMulti-Class Classification Report:")
print(classification_report(y_test_multi, y_pred_multi))

# Confusion Matrix
cm_multi = confusion_matrix(y_test_multi, y_pred_multi)

plt.figure(figsize=(8,6))
sns.heatmap(cm_multi, annot=True, fmt='d', cmap='Reds')
plt.title("Multi-Class Confusion Matrix")
plt.show()

# ============================================================
# 6. SAVE MODELS
# ============================================================
joblib.dump(binary_model, "binary_ddos_model.pkl")
joblib.dump(multi_model, "multiclass_ddos_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(le_multi, "label_encoder_multi.pkl")

print("\n✅ Models saved successfully!")

"""# **Comparison Among the Models**"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Deep Learning
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Random Forest": RandomForestClassifier(n_estimators=150, random_state=42),
    "SVM": SVC(kernel='rbf'),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "XGBoost": XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        eval_metric="logloss",
        random_state=42
    )
}

# ============================================================
# TWO-STAGE DDoS DETECTION (IMBALANCE-AWARE FINAL VERSION)
# ============================================================

import pandas as pd
import numpy as np
import joblib

# ML Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

# Preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Deep Learning
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

# Visualization
import seaborn as sns
import matplotlib.pyplot as plt

# ============================================================
# 1. LOAD DATA
# ============================================================
train_df = pd.read_csv("train_balanced.csv")
test_df  = pd.read_csv("test_fixed.csv")

# ============================================================
# 2. FEATURES
# ============================================================
features = [
    "Flow Duration","Total Fwd Packets","Fwd Packets Length Total",
    "Flow IAT Mean","Flow IAT Std","Fwd IAT Mean","Fwd IAT Min","Fwd IAT Std",
    "Total Backward Packets","Bwd Packets Length Total","Down/Up Ratio",
    "Packet Length Mean","Packet Length Std","Avg Packet Size",
    "SYN Flag Count","ACK Flag Count","RST Flag Count","Protocol"
]

# ============================================================
# 3. CLEAN DATA (NO MISALIGNMENT)
# ============================================================
train_clean = train_df[features + ["Binary_Label","Attack_Type"]].copy()
test_clean  = test_df[features + ["Binary_Label","Attack_Type"]].copy()

train_clean.replace([np.inf, -np.inf], np.nan, inplace=True)
test_clean.replace([np.inf, -np.inf], np.nan, inplace=True)

train_clean.fillna(0, inplace=True)
test_clean.fillna(0, inplace=True)

# ============================================================
# 4. SPLIT
# ============================================================
X_train = train_clean[features]
y_train = train_clean["Binary_Label"]

X_test = test_clean[features]
y_test = test_clean["Binary_Label"]

# ============================================================
# 5. SCALING
# ============================================================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

print("Train:", X_train.shape, y_train.shape)
print("Test :", X_test.shape, y_test.shape)

# ============================================================
# 6. HANDLE IMBALANCE
# ============================================================
neg, pos = np.bincount(y_train)
scale_pos_weight = neg / pos

print(f"Scale_pos_weight: {scale_pos_weight:.2f}")

# ============================================================
# 7. MODELS (IMBALANCE FIXED)
# ============================================================
models = {
    "Logistic Regression": LogisticRegression(max_iter=500, class_weight='balanced'),

    "Random Forest": RandomForestClassifier(
        n_estimators=150,
        class_weight='balanced',
        random_state=42
    ),

    "SVM": SVC(class_weight='balanced'),

    "KNN": KNeighborsClassifier(n_neighbors=5),

    "XGBoost": XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        scale_pos_weight=scale_pos_weight,
        eval_metric="logloss",
        random_state=42
    )
}

# ============================================================
# 8. TRAIN + EVALUATE
# ============================================================
results = []

print("\n===== STAGE 1: BINARY MODEL COMPARISON =====")

for name, model in models.items():
    print(f"\n🔹 Training: {name}")

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    report = classification_report(y_test, y_pred, output_dict=True)

    acc = accuracy_score(y_test, y_pred)
    f1_attack = report['1']['f1-score']
    recall_attack = report['1']['recall']
    precision_attack = report['1']['precision']

    results.append([name, acc, f1_attack, precision_attack, recall_attack])

    print(classification_report(y_test, y_pred))

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(4,3))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f"{name} Confusion Matrix")
    plt.show()

# ============================================================
# 9. DEEP LEARNING (WITH CLASS WEIGHTS)
# ============================================================
print("\n🔹 Training: Deep Learning Model")

from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weight_dict = {0: class_weights[0], 1: class_weights[1]}

y_train_dl = to_categorical(y_train)
y_test_dl  = to_categorical(y_test)

dl_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(2, activation='softmax')
])

dl_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

dl_model.fit(
    X_train, y_train_dl,
    epochs=10,
    batch_size=256,
    class_weight=class_weight_dict,
    verbose=1
)

y_pred_dl = np.argmax(dl_model.predict(X_test), axis=1)

report = classification_report(y_test, y_pred_dl, output_dict=True)

results.append([
    "Deep Learning",
    accuracy_score(y_test, y_pred_dl),
    report['1']['f1-score'],
    report['1']['precision'],
    report['1']['recall']
])

# ============================================================
# 10. FINAL COMPARISON
# ============================================================
results_df = pd.DataFrame(results, columns=[
    "Model","Accuracy","F1_Attack","Precision_Attack","Recall_Attack"
])

print("\n===== FINAL RESULTS =====")
print(results_df.sort_values(by="F1_Attack", ascending=False))

# ============================================================
# 11. BEST MODEL
# ============================================================
best_model = results_df.sort_values(by="F1_Attack", ascending=False).iloc[0]
print("\n🏆 BEST MODEL:")
print(best_model)

# ============================================================
# 12. STAGE 2 (MULTI-CLASS)
# ============================================================
print("\n===== STAGE 2: MULTI-CLASS =====")

train_ddos = train_clean[train_clean["Binary_Label"] == 1]
test_ddos  = test_clean[test_clean["Binary_Label"] == 1]

le = LabelEncoder()
y_train_multi = le.fit_transform(train_ddos["Attack_Type"])

known_classes = set(train_ddos["Attack_Type"])
test_ddos = test_ddos[test_ddos["Attack_Type"].isin(known_classes)]

X_train_ddos = scaler.transform(train_ddos[features])
X_test_ddos  = scaler.transform(test_ddos[features])

y_test_multi = le.transform(test_ddos["Attack_Type"])

multi_model = XGBClassifier(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    eval_metric="mlogloss"
)

multi_model.fit(X_train_ddos, y_train_multi)
y_pred_multi = multi_model.predict(X_test_ddos)

print(classification_report(y_test_multi, y_pred_multi))

# ============================================================
# 13. SAVE
# ============================================================
joblib.dump(multi_model, "multiclass_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(le, "label_encoder.pkl")

print("\n✅ DONE: Models saved")



"""# **Advanced Grouping**"""

# ============================================================
# ADVANCED GROUPED DDoS CLASSIFICATION (RESEARCH EXPERIMENT)
# ============================================================

import pandas as pd
import numpy as np
from sklearn.utils import resample
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier
import seaborn as sns
import matplotlib.pyplot as plt

# ============================================================
# 1. LOAD DATA
# ============================================================
train_df = pd.read_csv("train_fixed.csv")
test_df  = pd.read_csv("test_fixed.csv")

# ============================================================
# 2. ADVANCED GROUPING
# ============================================================
def group_attack(x):
    x = str(x)

    if x == "Benign":
        return "Benign"

    elif x in ["UDP", "UDPLag", "DNS", "NTP", "SNMP", "TFTP"]:
        return "UDP_Family"

    elif x in ["MSSQL", "NetBIOS", "LDAP"]:
        return "TCP_Service"

    elif x == "Syn":
        return "SYN_Flood"

    elif x == "Portmap":
        return "Reflection"

    else:
        return "Other"

train_df["Grouped_Label"] = train_df["Attack_Type"].apply(group_attack)
test_df["Grouped_Label"]  = test_df["Attack_Type"].apply(group_attack)

print("\nTraining Distribution (Grouped):")
print(train_df["Grouped_Label"].value_counts())

print("\nTesting Distribution (Grouped):")
print(test_df["Grouped_Label"].value_counts())

# ============================================================
# 3. BALANCE TRAINING DATA
# ============================================================
df_list = []

for label in train_df["Grouped_Label"].unique():
    df_class = train_df[train_df["Grouped_Label"] == label]

    if len(df_class) < 3000:
        df_class = resample(
            df_class,
            replace=True,
            n_samples=3000,
            random_state=42
        )

    df_list.append(df_class)

train_balanced = pd.concat(df_list)

print("\nBalanced Distribution:")
print(train_balanced["Grouped_Label"].value_counts())

# ============================================================
# 4. FEATURE SELECTION
# ============================================================
features = [
    "Flow Duration",
    "Total Fwd Packets",
    "Fwd Packets Length Total",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Fwd IAT Mean",
    "Fwd IAT Min",
    "Fwd IAT Std",
    "Total Backward Packets",
    "Bwd Packets Length Total",
    "Down/Up Ratio",
    "Packet Length Mean",
    "Packet Length Std",
    "Avg Packet Size",
    "SYN Flag Count",
    "ACK Flag Count",
    "RST Flag Count",
    "Protocol"
]

# ============================================================
# 5. PREPARE DATA
# ============================================================
X_train = train_balanced[features]
X_test  = test_df[features]

# Cleaning
X_train.replace([np.inf, -np.inf], np.nan, inplace=True)
X_test.replace([np.inf, -np.inf], np.nan, inplace=True)

X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ============================================================
# 6. LABEL ENCODING
# ============================================================
le = LabelEncoder()
y_train = le.fit_transform(train_balanced["Grouped_Label"])
y_test  = le.transform(test_df["Grouped_Label"])

print("\nLabel Mapping:")
print(dict(zip(le.classes_, le.transform(le.classes_))))

# ============================================================
# 7. TRAIN MODEL
# ============================================================
model = XGBClassifier(
    n_estimators=300,
    max_depth=7,
    learning_rate=0.05,
    eval_metric="mlogloss",
    random_state=42
)

model.fit(X_train_scaled, y_train)

# ============================================================
# 8. EVALUATION
# ============================================================
y_pred = model.predict(X_test_scaled)

print("\nGrouped Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens')
plt.title("Grouped Confusion Matrix")
plt.show()

import pandas as pd
dataset = pd.read_csv('train_balanced.csv')
print("Columns in the dataset:", dataset.columns.tolist())
print("Number of columns:", len(dataset.columns))
dataset.head()